import React, { useEffect, useState } from 'react';
import client from '@/api/client';
import { DoctorAnalytics } from '@/types';
import { BarChart3, Clock, CheckCircle2, FileText, Pill } from 'lucide-react';

export const DoctorAnalyticsPage: React.FC = () => {
  const [data, setData] = useState<DoctorAnalytics | null>(null);

  useEffect(() => {
    client.get('/analytics/doctor').then(res => setData(res.data));
  }, []);

  if (!data) return <div className="p-8 text-center text-slate-500">Loading analytics...</div>;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Doctor Productivity & Insights</h1>
        <p className="text-slate-500 text-sm">Personal performance metrics and time savings generated by AI assistance.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase">Consultations</p>
          <h3 className="text-3xl font-bold text-slate-900 mt-2">{data.total_consultations}</h3>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase">Reports Generated</p>
          <h3 className="text-3xl font-bold text-slate-900 mt-2">{data.total_documents}</h3>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase">Finalized Reports</p>
          <h3 className="text-3xl font-bold text-slate-900 mt-2">{data.finalized_documents}</h3>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
          <p className="text-xs font-semibold text-slate-500 uppercase">Estimated Hours Saved</p>
          <h3 className="text-3xl font-bold text-emerald-600 mt-2">{data.estimated_hours_saved} hrs</h3>
        </div>
      </div>
    </div>
  );
};
